-- CREATE TABLE CUSTOMER (
--     CUSTOMERID CHAR(6),
--     CUSTOMERFIRSTNAME VARCHAR(64),
--     CUSTOMERLASTNAME VARCHAR(64),
--     STREETADDRESS1 VARCHAR(128),
--     STREETADDRESS2 VARCHAR(128),
--     CITY VARCHAR(32),
--     STATEORPROVINCE VARCHAR(32),
--     POSTALCODE CHAR(12),
--     COUNTRY VARCHAR(64),
--     HOMEPHONE VARCHAR(64),
--     MOBILEPHONE VARCHAR(64),
--     PRIMARYEMAILADDRESS VARCHAR(128),
--     SECONDARYEMAILADDRESS VARCHAR(128)
-- );

INSERT INTO CUSTOMER (
    CUSTOMERID, CUSTOMERFIRSTNAME, CUSTOMERLASTNAME,
    STREETADDRESS1, STREETADDRESS2, CITY, STATEORPROVINCE,
    POSTALCODE, COUNTRY, HOMEPHONE, MOBILEPHONE,
    PRIMARYEMAILADDRESS, SECONDARYEMAILADDRESS
) VALUES (
    '000001', 'KENTA', 'KOSUGI', 'xxxxxx', 'xxxxxxx', 'Koto', 'Tokyo',
    'xxxxx', 'Japan', null, '080xxxxxxxx', 'kkosugi@redhat.com', 'kenta.kosugi@gmail.com'
);